config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :garden_groups

  resources :gardens

  resources :sections

  resources :divisions

  resources :prune_types

  resources :yield_categories

  resources :section_yield_categories

  resources :section_prune_types

  resources :section_bush_types

  resources :bush_types

  resources :section_divisions

  resources :section_yields

  resources :section_vacancies

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/bush_type.rb
class BushType < ActiveRecord::Base
  has_many :section_bush_types
end

app/models/division.rb
class Division < ActiveRecord::Base
  belongs_to :garden
  has_many :section_divisions
end

app/models/garden.rb
class Garden < ActiveRecord::Base
  belongs_to :garden_group
  has_many :divisions
  has_many :sections
end

app/models/garden_group.rb
class GardenGroup < ActiveRecord::Base
  has_many :gardens
end

app/models/prune_type.rb
class PruneType < ActiveRecord::Base
  has_many :section_prune_types
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :garden
  has_many :section_yield_categories
  has_many :section_prune_types
  has_many :section_bush_types
  has_many :section_divisions
  has_many :section_yields
  has_many :section_vacancies
end

app/models/section_bush_type.rb
class SectionBushType < ActiveRecord::Base
  belongs_to :section
  belongs_to :bush_type
end

app/models/section_division.rb
class SectionDivision < ActiveRecord::Base
  belongs_to :section
  belongs_to :division
end

app/models/section_prune_type.rb
class SectionPruneType < ActiveRecord::Base
  belongs_to :section
  belongs_to :prune_type
end

app/models/section_vacancy.rb
class SectionVacancy < ActiveRecord::Base
  belongs_to :section
end

app/models/section_yield.rb
class SectionYield < ActiveRecord::Base
  belongs_to :section
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yield_category.rb
class YieldCategory < ActiveRecord::Base
  has_many :section_yield_categories
end

app/controllers/yield_categories_controller.rb
class YieldCategoriesController < ApplicationController
  before_action :set_yield_category, only: [:show, :edit, :update, :destroy]

  # GET /yield_categories
  # GET /yield_categories.json
  def index
    @yield_categories = YieldCategory.all
  end

  # GET /yield_categories/1
  # GET /yield_categories/1.json
  def show
  end

  # GET /yield_categories/new
  def new
    @yield_category = YieldCategory.new
  end

  # GET /yield_categories/1/edit
  def edit
  end

  # POST /yield_categories
  # POST /yield_categories.json
  def create
    @yield_category = YieldCategory.new(yield_category_params)

    respond_to do |format|
      if @yield_category.save
        format.html { redirect_to @yield_category, notice: 'Yield category was successfully created.' }
        format.json { render :show, status: :created, location: @yield_category }
      else
        format.html { render :new }
        format.json { render json: @yield_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yield_categories/1
  # PATCH/PUT /yield_categories/1.json
  def update
    respond_to do |format|
      if @yield_category.update(yield_category_params)
        format.html { redirect_to @yield_category, notice: 'Yield category was successfully updated.' }
        format.json { render :show, status: :ok, location: @yield_category }
      else
        format.html { render :edit }
        format.json { render json: @yield_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yield_categories/1
  # DELETE /yield_categories/1.json
  def destroy
    @yield_category.destroy
    respond_to do |format|
      format.html { redirect_to yield_categories_url, notice: 'Yield category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yield_category
      @yield_category = YieldCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yield_category_params
      params.require(:yield_category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bush_types_helper.rb
module BushTypesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/garden_groups_helper.rb
module GardenGroupsHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/prune_types_helper.rb
module PruneTypesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/yield_categories_helper.rb
module YieldCategoriesHelper
end

app/views/yield_categories/_form.html.erb
<%= form_for @yield_category, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  yield_categories_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/yield_categories/edit.html.erb
<%- model_class = YieldCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => YieldCategory %></h1>
</div>
<%= render :partial => 'form' %>

app/views/yield_categories/index.html.erb
<%- model_class = YieldCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => YieldCategory %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @yield_categories.each do |yield_category| %>
      <tr>
        <td><%= yield_category.id %></td>
        <td><%= yield_category.name %></td>
        <td><%=l yield_category.created_at, format: :long %></td>
        <td>
          <%= link_to yield_category_path(yield_category), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to yield_category_path(yield_category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_yield_category_path,
            :class => 'btn btn-primary' %>

app/views/yield_categories/new.html.erb
<%- model_class = YieldCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => YieldCategory %></h1>
</div>
<%= render :partial => 'form' %>

app/views/yield_categories/show.html.erb
<%- model_class = YieldCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => YieldCategory %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @yield_category.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              yield_categories_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_yield_category_path(@yield_category), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              yield_category_path(@yield_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>