config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :garden_groups

  resources :gardens

  resources :sections

  resources :divisions

  resources :prune_types

  resources :yield_categories

  resources :section_yield_categories

  resources :section_prune_types

  resources :section_bush_types

  resources :bush_types

  resources :section_divisions

  resources :section_yields

  resources :section_vacancies

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/bush_type.rb
class BushType < ActiveRecord::Base
  has_many :section_bush_types
end

app/models/division.rb
class Division < ActiveRecord::Base
  belongs_to :garden
  has_many :section_divisions
end

app/models/garden.rb
class Garden < ActiveRecord::Base
  belongs_to :garden_group
  has_many :divisions
  has_many :sections
end

app/models/garden_group.rb
class GardenGroup < ActiveRecord::Base
  has_many :gardens
end

app/models/prune_type.rb
class PruneType < ActiveRecord::Base
  has_many :section_prune_types
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :garden
  has_many :section_yield_categories
  has_many :section_prune_types
  has_many :section_bush_types
  has_many :section_divisions
  has_many :section_yields
  has_many :section_vacancies
end

app/models/section_bush_type.rb
class SectionBushType < ActiveRecord::Base
  belongs_to :section
  belongs_to :bush_type
end

app/models/section_division.rb
class SectionDivision < ActiveRecord::Base
  belongs_to :section
  belongs_to :division
end

app/models/section_prune_type.rb
class SectionPruneType < ActiveRecord::Base
  belongs_to :section
  belongs_to :prune_type
end

app/models/section_vacancy.rb
class SectionVacancy < ActiveRecord::Base
  belongs_to :section
end

app/models/section_yield.rb
class SectionYield < ActiveRecord::Base
  belongs_to :section
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yield_category.rb
class YieldCategory < ActiveRecord::Base
  has_many :section_yield_categories
end

app/controllers/section_prune_types_controller.rb
class SectionPruneTypesController < ApplicationController
  before_action :set_section_prune_type, only: [:show, :edit, :update, :destroy]

  # GET /section_prune_types
  # GET /section_prune_types.json
  def index
    @section_prune_types = SectionPruneType.all
  end

  # GET /section_prune_types/1
  # GET /section_prune_types/1.json
  def show
  end

  # GET /section_prune_types/new
  def new
    @section_prune_type = SectionPruneType.new
  end

  # GET /section_prune_types/1/edit
  def edit
  end

  # POST /section_prune_types
  # POST /section_prune_types.json
  def create
    @section_prune_type = SectionPruneType.new(section_prune_type_params)

    respond_to do |format|
      if @section_prune_type.save
        format.html { redirect_to @section_prune_type, notice: 'Section prune type was successfully created.' }
        format.json { render :show, status: :created, location: @section_prune_type }
      else
        format.html { render :new }
        format.json { render json: @section_prune_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /section_prune_types/1
  # PATCH/PUT /section_prune_types/1.json
  def update
    respond_to do |format|
      if @section_prune_type.update(section_prune_type_params)
        format.html { redirect_to @section_prune_type, notice: 'Section prune type was successfully updated.' }
        format.json { render :show, status: :ok, location: @section_prune_type }
      else
        format.html { render :edit }
        format.json { render json: @section_prune_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /section_prune_types/1
  # DELETE /section_prune_types/1.json
  def destroy
    @section_prune_type.destroy
    respond_to do |format|
      format.html { redirect_to section_prune_types_url, notice: 'Section prune type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section_prune_type
      @section_prune_type = SectionPruneType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_prune_type_params
      params.require(:section_prune_type).permit(:year, :section_id, :prune_type_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bush_types_helper.rb
module BushTypesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/prune_types_helper.rb
module PruneTypesHelper
end

app/helpers/section_prune_types_helper.rb
module SectionPruneTypesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/section_prune_types/_form.html.erb
<%= form_for @section_prune_type, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :year, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :year, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  section_prune_types_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/section_prune_types/edit.html.erb
<%- model_class = SectionPruneType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => SectionPruneType %></h1>
</div>
<%= render :partial => 'form' %>

app/views/section_prune_types/index.html.erb
<%- model_class = SectionPruneType -%>
<div class="page-header">
  <h1><%=t '.title', :default => SectionPruneType %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @section_prune_types.each do |section_prune_type| %>
      <tr>
        <td><%= section_prune_type.id %></td>
        <td><%= section_prune_type.year %></td>
        <td><%=l section_prune_type.created_at, format: :long %></td>
        <td>
          <%= link_to section_prune_type_path(section_prune_type), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to section_prune_type_path(section_prune_type), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_section_prune_type_path,
            :class => 'btn btn-primary' %>

app/views/section_prune_types/new.html.erb
<%- model_class = SectionPruneType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => SectionPruneType %></h1>
</div>
<%= render :partial => 'form' %>

app/views/section_prune_types/show.html.erb
<%- model_class = SectionPruneType -%>
<div class="page-header">
  <h1><%=t '.title', :default => SectionPruneType %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:year) %></dt>
      <dd><pre class="prettyprint"><%= @section_prune_type.year %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              section_prune_types_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_section_prune_type_path(@section_prune_type), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              section_prune_type_path(@section_prune_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>